### ISSUE TITLE
Fix cargo clippy warnnings

### ISSUE THREAD

**Issue by cathay4t** [rust-netlink/xfrmnetlink#2]
* Run `cargo fmt`
 * For the too many arguments. Please use the same way as [`rtnetlink::RouteAddRequest`][1].
 * The `add_template()` should just take `UserTemplate` instead all the properties of it. If you want make it easy to use. You should add function like `UserTemplate::set_ip(ip: IpAddr)` instead of do it at `PolicyModifyRequest`. We create struct in the hope of isolation, not mixing stuff between files.

[1]: https://docs.rs/rtnetlink/latest/rtnetlink/struct.AddressDelRequest.html

**Comment by zooknotic** [comment]
Take a look at the PRs I've attached here and on netlink-packet-xfrm at https://github.com/rust-netlink/netlink-packet-xfrm/pull/6
I think the main points above are addressed, though I'm not sure why the CI actions are failing.
